Acceptance testing
Alexander-Andrade/stack_overflow pull request #3
Opened 2017-03-29 19:49 UTC by Alexander-Andrade

2017-03-30 19:29 UTC, vkurennov requested changes

2017-03-30 19:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy!
Тут должна быть провверка на автора, иначе, можно легко удалить чужой ответ, отправив запрос в обход интерфейса

2017-03-30 19:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = @answer.question
Переменная не нужна, можно сразу подставить `@answer.question`  в `redirect_to`. После удаления ответа, он еще есть в памяти и его ассоциации тоже

2017-03-30 19:29 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.destroy!
Тут нужна проверка на автора

2017-03-30 19:29 UTC, vkurennov commented on app/models/answer.rb
> +  validates :user_id, presence: true
Не нужно валидировать поля ассоциаций, т.к. при наличии ассоциации `belongs_to` это происходит автоматически, а у тебя выходит проверка дважды.

2017-03-30 19:29 UTC, vkurennov commented on app/models/question.rb
> +  validates :user_id, presence: true
И опять лишняя валидация

2017-03-30 19:29 UTC, vkurennov commented on app/views/questions/_actions_dropdown.html.slim
> +.dropdown
Паршл очень похож на тот, что используется в answers, сделай его универсальным, а пути и прочее передавай параметрами

2017-03-30 19:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      - if current_user == @question.user
Лучше проверять по user_id, так ты не будешь делать лишний запрос к базе. И такая проверка нужна будет еще не раз, поэтому лучше вынести ее в метод `User#author_of?`

2017-03-30 19:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +            - if current_user == answer.user
Замени на `User#author_of?`

2017-03-30 19:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render(partial:'answers/form', locals:{question: @question})
У render не ставятс скобки, вообще у всех хелперов в видах принято скобки не ставить, их ставим только у других методов.

2017-03-30 19:29 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, only: [:destroy]
Прочитай раздел 2.7.2 про shallow resources [здесь](http://guides.rubyonrails.org/routing.html#nested-resources)

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/browse_question_its_answers_spec.rb
> +    expect(page).to have_content question.title
А юзер видит только заголовок вопроса?

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully created.'
Надо проверить текст ответа на странице

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'The answer is invalid.'
Тут надо проверить стандартные ошибки валидации, а не то, что ты из контроллера выводишь

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Test Question'
А тело вопроса не отображается?

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий с невалидным вопросом

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully deleted.'
Нужно проверить, что текста ответа больше нет на странице, а перед удалением то, что он есть

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Your question successfully deleted.'
Тут тоже надо до удаления проверить наличие текста вопроса на странице, а после - его отсутсвие.

2017-03-30 19:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут нужен еще один тест на то, что ответ связывается с залогиненным юзером

2017-03-30 19:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Тут нужно проверить, что вопрос связывается с залогиненным юзером

2017-03-30 19:29 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А тесты на ассоциации?

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/browse_question_its_answers_spec.rb
> +      expect(page).to have_content a.content
Логика верная, но тест ложно-положительный, т.к. у тебя все ответы генерируются одинаковыми и мы можем просто 3 раза проверить один и тот же текст. Используй sequence в  фабриках, чтобы сделать ответы разными.

2017-03-30 19:29 UTC, vkurennov commented on spec/acceptance/browse_question_list_spec.rb
> +  given!(:questions) { create_list(:question, 3, user: user) }
Используй sequence в  фабриках, чтобы сделать вопросы разными.

2017-03-31 16:21 UTC, Alexander-Andrade commented on spec/acceptance/browse_question_its_answers_spec.rb
> +    expect(page).to have_content question.title
Юзер видит и тело тоже

2017-03-31 16:21 UTC, Alexander-Andrade commented on spec/acceptance/browse_question_its_answers_spec.rb
> +    expect(page).to have_content question.title
сейчас добавлю проверку

2017-03-31 18:29 UTC, Alexander-Andrade commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Test Question'
отображается, исправлю тест

2017-04-01 04:37 UTC, vkurennov requested changes

2017-04-01 04:37 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:error] = @answer.errors.full_messages.join(';')
Не нужно выводить ошибки через флеш-сообщение, сделай вывод в форме ответа, как это стандартно делается.

2017-04-01 04:37 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Если делать редирект, то потеряется и то, что ввел пользователь и ошибки валидации (если флеш не использовать, конечно)

2017-04-01 04:37 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +      = render 'shared/error_messages', object: f.object
Вот же вывод ошибок. Зачем тогда в контроллере это делать? Видимо из-за того, что при редиректе ошибки не выводятся?

2017-04-01 04:37 UTC, vkurennov commented on app/views/questions/show.html.slim
> +            - if current_user and current_user.author_of? answer
Не используй  `and, or, not`, вместо них используй `&&, ||, !`. У первых низкий приотритет выполнения, это может вести к неочевидным и сложным багам.

2017-04-01 04:37 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
А где тесты на destroy?

2017-04-01 04:37 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
И тут нет тестов на destroy

2017-04-01 04:37 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
В модели есть еще и метод `author_of?`, его тоже надо тестировать. Вообще, если пишешь или изменяешь код в каком-либо классе, проверь, есть ли у тебя тесты на этот код, если нет - напиши.

2017-04-15 15:49 UTC, Alexander-Andrade commented on app/controllers/answers_controller.rb
> +      redirect_to @question
вместо redirect сделал отдельный view для экшена new

2017-04-16 08:07 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Зачем? можно же просто отрендерить страницу вопроса

2017-04-16 08:13 UTC, vkurennov approved these changes

2017-04-16 08:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        redirect_to @question
В случае, если объект невалидный, надо отрендерить страницу вопроса, на которой и есть форма ответа.

2017-04-16 08:13 UTC, vkurennov commented on app/views/answers/new.html.slim
> += render(partial:'answers/form', locals:{question: @question, answer: @answer})
Не ставятся скобки у render

2017-04-16 08:13 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        span.pull-right = render(partial:'shared/actions_dropdown', locals:{item_path: @question})
Скобки у render не ставятся

2017-04-16 08:13 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'registered user is an current user' do
Это лишний тест, он не влияет на удаление, это ты проверил, верно ли работает хелпер sign_in_user

2017-04-16 08:13 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(own_question)).to eq true
В юнит-тестах принято правило "один тест - один expect", старайся его придерживатсья.

И еще можно для методов-предикатов писать так:

`expect(user).to be_author_of?(own_question)`

2017-04-16 09:57 UTC, Alexander-Andrade commented on app/controllers/answers_controller.rb
>        redirect_to @question
Как понимаю, это будет сложно сделать, redirect_to делает новый запрос к контроллеру questions и экшену show,
в данном случае ошибки валидации можно передать через flash.
Если попытаться сделать render 'questions#show' из экшена 'answers#create', то url будет соответствовать   'answers#create', поэтому пришлось сделать новый view 'answers/new' и тогда ошибки валидации будут показаны в этой форме.

Вот тут смотрел похожий вопрос: http://stackoverflow.com/questions/20368717/rails-i-cant-pass-a-validation-error-in-a-redirect

2017-04-16 10:13 UTC, merged